### ISSUE TITLE
不设置布局的长按点击事件，长按条目程序会崩溃

### ISSUE THREAD

**Issue by liuly0218** [LRH1993/AutoFlowLayout#2]
如果不设置布局的长按点击事件或不单独设置条目的长按点击事件，那么长按条目程序会崩溃，错误信息如下：
java.lang.NullPointerException: Attempt to invoke interface method 'void com.example.library.AutoFlowLayout$OnLongItemClickListener.onLongItemClick(int, android.view.View)' on a null object reference
希望修复这个bug

**Comment by LRH1993** [comment]
已修复，多谢提醒
