### ISSUE TITLE
普通流式标签场景点击添加删除单行多行有问题

### ISSUE THREAD

**Issue by getglory** [LRH1993/AutoFlowLayout#3]
SpecialFlowActivity第56行没有把view强转为ImageView
普通流式标签场景点击添加删除单行多行有问题

**Comment by LRH1993** [comment]
那个是view.findViewById 不需要强转  添加删除需要在数据都展示出来才可以。如果通过单行或多行控制只展示一部分数据，那个使用添加删除，会有问题。这一部分后面会优化。
